### ISSUE TITLE
Infografías

### ISSUE THREAD

**Issue by estefigran** [estefigran/vasava#1]
## EPIC
#2 
## Description
Como equipo de marketing, necesitamos crear piezas educativas como parte del plan de awarness de criptoactivos para empleados banco. 

## Proposed work

Crear dos infografías 
Infografía sobre el ETF de bitcoin.
Infografía sobre las criptomonedas en general. 

## Definition of Done

Envíar infografías según especificaciones enviadas por correo. 

Nota: Debe ir con marca Bancolombia

**Comment by estefigran** [comment]
hfsjfsjf

**Comment by uxuevasava** [comment]
@estefigran me podrías pasar las dimensiones porfa? Gracias!
